controller_frequency: 5.0
recovery_behavior_enabled: false
clearing_rotation_allowed: false

TrajectoryPlannerROS:
   max_vel_x: 0.2
   min_vel_x: 0.0
   max_vel_y: 0.2  
   min_vel_y: 0.0
   max_vel_theta: 0.1
   min_vel_theta: -0.1
   acc_lim_x: 0.2
   acc_lim_y: 0.2
   acc_lim_theta: 0.1
   y_vels: [-0.05, -0.01, 0.01, 0.05]

   holonomic_robot: false
   yaw_goal_tolerance: 0.1 # about 6 degrees
   xy_goal_tolerance: 0.1  
   latch_xy_goal_tolerance: false
   pdist_scale: 0.4
   gdist_scale: 0.8
   meter_scoring: true

   heading_lookahead: 0.325
   heading_scoring: false
   heading_scoring_timestep: 0.8
   occdist_scale: 0.05
   oscillation_reset_dist: 0.05
   publish_cost_grid_pc: false
   prune_plan: true

   sim_time: 2.0
   sim_granularity: 0.02
   angular_sim_granularity: 0.1
   vx_samples: 8
   vy_samples: 8  
   vtheta_samples: 20
   dwa: true
   simple_attractor: false